tasks/run_cd4pe_job.rb

With this change, we fix a problem causing SSL users with chained
(intermediate) ssl ca certs to be unable to run jobs. With this change
we change the way we user Net::Http to handle chained SSL certs.

CDPE-3003 Jobs fail for chained ssl certs

---

tasks/run_cd4pe_job.rb

This adds a nil check for the ca_cert_file when we are deciding whether or not to create an X509 store so that if https is enabled but we don't have a cert, we don't create the store as creating the store in that scenario was causing all jobs to fail with the elegant 'system lib' error message.

CDPE-3018 adds check for ca_cert_file

---

spec/run_cd4pe_job_spec.rb
tasks/run_cd4pe_job.rb

With this change, we add the --rm flag to our docker run command to
ensure that the docker container gets removed after each docker-based
job  execution.
I also fixed a broken unit test related to 'make_dir'.
Test executed:
I ran 4 jobs with the old code, and then ran a `sudo docker ps -a` on the puppet agent that ran the job. All 4 containers were still mounted. 
I implemented the change, and ran the same test, monitoring the state of `sudo docker ps -a` during the job runs. The containers were spun up, and then removed.

CDPE-3032: Delete docker container after job run

---

tasks/run_cd4pe_job.rb

With this change, we pull the latest docker image with each job run,
if a docker image is supplied (if it is a docker-based job).
Testing:
I validated this works if:
1. no image exists locally.
2. an out-of-date image exists locally.
3. an up-to-date image exists locally.

CDPE-3044: Update docker image on each job run

---

tasks/run_cd4pe_job.rb

This ensures the path and query parameters are correctly formatted. Previously the path being passed included `scheme://host:port`, which is considered an invalid path by some routing systems (such as Envoy).
Signed-off-by: Michael Smith <michael.smith@puppet.com>

CDPE-3069: Pass URI object to HTTP requests

---

README.md
spec/run_cd4pe_job_spec.rb
tasks/run_cd4pe_job.rb

Prior to this change, jobs run via orchestrator on a puppet agent would
not have their $HOME env var set, causing problems for many common
tasks run inside jobs, such as `bundle pdk install`. We also had no way
for the writer of the cd4pe job script to reference the control repo
they wished to run tests on, forcing them to use a relative path in
their job script to locate the repos dir.
With this change, we set the $HOME var on the puppet agent before
executing the job script so it is accessible for the duration of the
job, and the $REPO_DIR var to the parent of the control repo so the
cd4pe job script writer can reliably access the control repo.
**Testing:**
I updated my PE master with this code, created two test machines: Centos and Windows, and ran jobs on both, ensuring I could …

CDPE-3177: Set HOME and REPO_DIR env vars

---

tasks/run_cd4pe_job.rb

Prior to this commit, we failed to set the $HOME environment variable on
windows machines due to a syntax error in the powershell command.
With this change, we remove the attempt to set the $HOME dir, as its
been made evident that $HOME is set by default on windows.

Maint: fix powershell HOME env var

---

tasks/run_cd4pe_job.rb

With this change, we send the detailed log output of Puppet
agent jobs to a new endpoint in CD4PE.
Prior to this commit, if a Puppet agent job produced too many log
entries, the Orchestrator would crash and the job would fail.
See detail from ticket `ORCH-2255`...
```
Any user using bolt with PXP will likely come across this. Users
will not expect there to be limitations when uploading a 5Mb file
or run a 1500 line script, both if which will cause orchestrator/PXP
to fall over completely. Users will expect this to work as it
works fine over SSH or WinRM.
```

CDPE-3250 Handle long Puppet agent job logs

---

tasks/run_cd4pe_job.rb

Prior to this change, there existed a bug in which executing a job with
a large stdout/stderr would cause a job to hang. This was due to the
fact that we were using Open3.popen2e, a function that exists to
execute system commands, and provide the caller a way to interact with
stdout/etderr on a line-by-line basis. popen2e, however, also requires
the caller to create another thread for safely tracking output. If the
second thread is not created/maintained, popen2e will hang on a large
stdout/stderr.
With this change, we replace our usage of popen2e with the higher-level
function, `capture2e`, which exists to capture stdout/stderr without the
caller having to manage multiple threads.
Reference:
https://docs.ruby-lang.org/en/2.5.0/Open3.html

CDPE-3390: Fix jobs hung by large stdout/err

---

tasks/run_cd4pe_job.rb

Prior to this commit, we implemented a new feature to send CD4PE job
logs directly from the puppet agent to a new CD4PE endpoint to avoid
problems with the Puppet orchestrator. However, we failed to make these
changes backwards compatible, such that customers consuming the CD4PE
jobs module would see failed jobs if they failed to update CD4PE to
3.10.0.
With this change, we add logic to handle this case, and fallback to the
old behavior if the customer is using a version of CD4PE 3.9.3 or lower.
**3.10.0 and higher logs:**
```
2020-06-08 22:09:57 UTC: Job instance 37 run complete.
2020-06-08 22:09:57 UTC: Sending logs to CD4PE.
2020-06-08 22:09:59 UTC: Job completed successfully!
```
**3.9.3 or lower logs:**
```
2020-06-08 22:48:18 UTC: Job instance 313 run complete.
2020-06-08 22:48:18 …
```

CDPE-3334: make module backwards compatible with CD4PE 3.9.3 and lower

---

tasks/run_cd4pe_job.rb

Prior to this change, when a cd4pe job sent logs to cd4pe, we
misinterpreted the response code, and also sent the logs to stdout.
This caused a bug where the job log would appear to have sent the logs
to cd4pe, thereby circumventing the need to send logs to stdout, but
would actually send logs to stdout on the sly, causing jobs with large
logs to hang.
With this change, we fix the response code handling to properly
interpret the response code from cd4pe.
**Testing**
Validated new code properly handles response code from cd4pe by performing and e2e test ensuring the job logs are sent to cd4pe, and NO output is sent to STDOUT.

CDPE-3457: fix res code handling when saving logs

---

spec/run_cd4pe_job_spec.rb
tasks/run_cd4pe_job.json
tasks/run_cd4pe_job.rb

Prior to this change, the run_cd4pe_job had a default of 10 minutes when
hitting a CD4PE endpoint. This worked fine for most users, but a few
customers with large git repos ran into this timeout, and needed it to
be configurable.
With this change, we add an optional parameter to the task to allow the
caller to specify a custom net http read timeout in seconds, and then
use this parameter to set the connection timeout on the Net:HTTP client.
Because this parameter is optional, this change is backwards compatible
with existing versions of CD4PE, and can be released independently.

CDPE-3033: Make http read timeout configurable

---

spec/run_cd4pe_job_spec.rb
tasks/run_cd4pe_job.json
tasks/run_cd4pe_job.rb

Prior to this change, we defaulted to a timeout of 10 minutes when
hitting CD4PE endpoints. With this change, we instead use the env var
'HTTP_READ_TIMEOUT_SECONDS' if set, otherwise we default to 10 minutes.

CDPE-3033: Use http read timeout env var to override connection timeouts 

---

spec/run_cd4pe_job_spec.rb
tasks/run_cd4pe_job.json
tasks/run_cd4pe_job.rb

Update the job task to accept a Docker config.json as a base64-encoded string. If provided, this file will be used when pulling the specified image to add custom registry credentials.

CDPE-3480: Update job to use registry creds if provided

---

tasks/run_cd4pe_job.rb

Prior to this commit, if a user had a separate filesystem mounted
on their cd4pe_working_dir, an airgap installation would fail to
run jobs because it attempted to create a hardlink between that
filesystem and the ca in /etc.
With this commit, we switch the hardlink to a symlink, which allows
it to cross filesystem boundaries.
Testing:
I manually tested this on 4.2.2.  A customer also tested it on https://puppetlabs.zendesk.com/agent/tickets/41870.

(CDPE-3886) Switch local registry cert from hardlink to symlink

---

spec/run_cd4pe_job_spec.rb
tasks/run_cd4pe_job.rb

This removed the deprecated File.exists and replaces with the Ruby 3.x File.exist. Needed for Puppet 8.

chore: File.exists -> File.exist

---

README.md

We realized that users might be referencing the `master` branch in their puppetfiles (and possibly other places). In order to not break anyone, we are renaming it back to `master` from `main`. This commit updates the readme accordingly.

(maint) Put default branch name back to master

---

.github/workflows/unit-test.yml
spec/run_cd4pe_job_spec.rb
tasks/run_cd4pe_job.rb

I don't completely understand what's going on, but somewhere in our 3-deep  powershell script execution, the exit code of the CD4PE job is getting swallowed and turned into 0 every time. This results in a lot of false positives for users running jobs on windows agents. By adding this exit statement, pdk test unit, for example, will exit 1 when tests fail now. Rejoice.

(CDPE-7090) Leverage $LASTEXITCODE for powershell jobs

---

tasks/run_cd4pe_job.json

This ensures that the task won't be displayed in PE. Customers are not expected to run it directly; it is only triggered by CD4PE.

(maint) Make jobs task private

---

tasks/run_cd4pe_job.rb

This commit adds logging to indicate that we fall back to assuming a local version of the job image when pulling it from the remote fails. This should help users recognize that the pull errors are red herrings in air-gapped installs, and that the job will proceed, assuming the image has been loaded into the runtime out of band.

(maint) Add logging when image pull fails
